### ISSUE TITLE
Server throws an error on login

### ISSUE THREAD

**Issue by zavolokas** [LlaziG/Listening-Habits#1]
Hello Mr. Lazar, there is an issue while I try to login with Spotify:
```json
{ 
   "level":"error",
   "message":"Cannot read property 'url' of undefinedCannot read property 'url' of undefined",
   "stack":"TypeError: Cannot read property 'url' of undefined at fetch.then.then.json (D:\zavolokas\NodeJS\Listening-Habits\server\routes\user.js:31:39)    at process._tickCallback (internal/process/next_tick.js:68:7)",
   "timestamp":"2019-10-29T19:15:36.915Z"
}
```

**Comment by LlaziG** [comment]
Thanks for sharing, looking into it today. :)

**Comment by LlaziG** [comment]
All set :)
